// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDziP5q9m7Q1j6gERx6omAoq731iAC-F6o',
    appId: '1:916946576287:web:ab34e1dd6a48c4643093aa',
    messagingSenderId: '916946576287',
    projectId: 'todo-app-10527',
    authDomain: 'todo-app-10527.firebaseapp.com',
    storageBucket: 'todo-app-10527.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBouhBox6i2_4BhK3txFptPN7B-dX75rE',
    appId: '1:916946576287:android:6efbaaaff080d5353093aa',
    messagingSenderId: '916946576287',
    projectId: 'todo-app-10527',
    storageBucket: 'todo-app-10527.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTDAuHo7j1Y9a9LwKfeSGTFuYLXmlDbxY',
    appId: '1:916946576287:ios:c4431fea6cfd6dab3093aa',
    messagingSenderId: '916946576287',
    projectId: 'todo-app-10527',
    storageBucket: 'todo-app-10527.appspot.com',
    iosClientId: '916946576287-56vdkqt8c2gkdr8n1ub07kk23s7684ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTDAuHo7j1Y9a9LwKfeSGTFuYLXmlDbxY',
    appId: '1:916946576287:ios:645a3986bd35b67d3093aa',
    messagingSenderId: '916946576287',
    projectId: 'todo-app-10527',
    storageBucket: 'todo-app-10527.appspot.com',
    iosClientId: '916946576287-moqud456imrel9sqk2mbm8tde5u9tqfv.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
